-- ============================================================================
-- Meal Prep — APPLICATION DATA (the verified ingredient DB, recipes, packaging,
-- week templates, and config that used to live hard-coded in js/data.js).
--
-- Native shapes are preserved EXACTLY so the verified numbers never drift:
--   * macros/amounts are `numeric` (arbitrary precision — 10.8, 0.42 stay exact)
--   * `conversions` / `base_macros` / `snacks_baseline` are JSONB (numbers preserved)
--   * recipe `base_macros` are stored EXPLICITLY (they intentionally differ from the
--     ingredient sum, e.g. Brami estimates) — the app never recomputes them on load
--   * recipe `slug` and lowercase ingredient `name` are the stable join keys the app
--     relies on (carb swap, packaging, weeksPlan, recipeKeyMap, etc.)
--
-- RLS: PUBLIC READ, AUTHENTICATED WRITE (same model as supabase/schema.sql).
-- Run this in the Supabase SQL Editor, then run supabase/seed_app.sql.
-- ============================================================================

create extension if not exists "pgcrypto";

-- Verified ingredient database (per standard unit + a conversions map) ---------
create table if not exists stock_ingredients (
    name        text primary key,           -- lowercase = the join key
    cal         numeric not null,
    prot        numeric not null,
    fat         numeric not null,
    fib         numeric not null,
    carb        numeric not null,
    conversions jsonb   not null default '{}'::jsonb
);

-- Recipes (verified) ----------------------------------------------------------
create table if not exists stock_recipes (
    slug         text primary key,          -- e.g. 'bagel', 'vegStirfry'
    title        text not null,
    "desc"       text,
    type         text,
    week         int[]  not null default '{}',
    base_macros  jsonb  not null,           -- {cal,prot,fat,fib,carb} — stored verbatim
    steps        text[] not null default '{}',
    freezer_tips text,
    scaling_tip  text,
    position     int                        -- preserves directory order
);

-- Recipe -> ingredient lines (name/amount/unit, ordered) ----------------------
create table if not exists stock_recipe_ingredients (
    id          bigint generated by default as identity primary key,
    recipe_slug text not null references stock_recipes(slug) on delete cascade,
    position    int  not null,
    name        text not null,
    amount      numeric not null,
    unit        text not null
);
create index if not exists idx_sri_recipe on stock_recipe_ingredients(recipe_slug);

-- Retail packaging (how bulk items are sold) ----------------------------------
create table if not exists packaging (
    name           text primary key,
    retail_unit    text,
    unit_label     text,
    grams_per_unit numeric,
    units_per_case int,
    case_label     text,
    verified       boolean default false
);

-- Preset week templates -------------------------------------------------------
create table if not exists week_plans (
    week      int primary key,
    breakfast text,
    lunch     text,
    dinner    text,
    dessert   text
);

-- Single-row app config (snacks baseline + defaults) --------------------------
create table if not exists app_config (
    id                 int primary key default 1,
    snacks_baseline    jsonb not null,
    base_calorie_goal  int not null default 1800,
    default_prep_days  int not null default 7,
    daily_snack_key    text,
    daily_snack_count  int,
    constraint app_config_singleton check (id = 1)
);

-- Single-row user settings — cross-device sync of the plan/preferences (calorie goal,
-- carb/units mode, meal selections, prep days). localStorage is the fast cache; this is the
-- source of truth when signed in. Writing requires auth (RLS), reading is public.
create table if not exists app_settings (
    id         int primary key default 1,
    data       jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    constraint app_settings_singleton check (id = 1)
);

-- ============================================================================
-- Row Level Security: public read, authenticated write
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array['stock_ingredients','stock_recipes','stock_recipe_ingredients','packaging','week_plans','app_config','app_settings']
  loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists "public read %1$s" on %1$I;', t);
    execute format('drop policy if exists "auth write %1$s" on %1$I;', t);
    execute format('create policy "public read %1$s" on %1$I for select using (true);', t);
    execute format('create policy "auth write %1$s" on %1$I for all to authenticated using (true) with check (true);', t);
  end loop;
end $$;
