// Generates supabase/seed_app.sql straight from js/data.js — NO retyping of the
// verified numbers. Run: node scripts/gen-seed.js
const fs = require('fs');
const path = require('path');
const { loadData } = require('./load-data');
const { buildRows } = require('./build-rows');

// ---- SQL value formatters --------------------------------------------------
function q(s) { return s == null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'"; }
function n(x) { return x == null ? 'null' : String(x); }                 // numeric / int (full precision)
function jb(o) { return "'" + JSON.stringify(o).replace(/'/g, "''") + "'::jsonb"; }
function intArr(a) { return "'{" + (a || []).join(',') + "}'::int[]"; }
function textArr(a) { return (a && a.length) ? 'ARRAY[' + a.map(q).join(',') + ']::text[]' : "ARRAY[]::text[]"; }
function b(v) { return v ? 'true' : 'false'; }

function values(rows, fn) { return rows.map(function (r) { return '  (' + fn(r) + ')'; }).join(',\n'); }

const rows = buildRows(loadData());
const out = [];
out.push('-- AUTO-GENERATED by scripts/gen-seed.js from js/data.js — do not hand-edit.');
out.push('-- Run AFTER supabase/schema_app.sql, in the Supabase SQL Editor.');
out.push('begin;');
out.push('truncate stock_recipe_ingredients, stock_recipes, stock_ingredients, packaging, week_plans, app_config restart identity cascade;');
out.push('');

out.push('insert into stock_ingredients (name, cal, prot, fat, fib, carb, conversions) values');
out.push(values(rows.stock_ingredients, function (r) {
    return [q(r.name), n(r.cal), n(r.prot), n(r.fat), n(r.fib), n(r.carb), jb(r.conversions)].join(', ');
}) + ';\n');

out.push('insert into stock_recipes (slug, title, "desc", type, week, base_macros, steps, freezer_tips, scaling_tip, position) values');
out.push(values(rows.stock_recipes, function (r) {
    return [q(r.slug), q(r.title), q(r.desc), q(r.type), intArr(r.week), jb(r.base_macros), textArr(r.steps), q(r.freezer_tips), q(r.scaling_tip), n(r.position)].join(', ');
}) + ';\n');

out.push('insert into stock_recipe_ingredients (recipe_slug, position, name, amount, unit) values');
out.push(values(rows.stock_recipe_ingredients, function (r) {
    return [q(r.recipe_slug), n(r.position), q(r.name), n(r.amount), q(r.unit)].join(', ');
}) + ';\n');

out.push('insert into packaging (name, retail_unit, unit_label, grams_per_unit, units_per_case, case_label, verified) values');
out.push(values(rows.packaging, function (r) {
    return [q(r.name), q(r.retail_unit), q(r.unit_label), n(r.grams_per_unit), n(r.units_per_case), q(r.case_label), b(r.verified)].join(', ');
}) + ';\n');

out.push('insert into week_plans (week, breakfast, lunch, dinner, dessert) values');
out.push(values(rows.week_plans, function (r) {
    return [n(r.week), q(r.breakfast), q(r.lunch), q(r.dinner), q(r.dessert)].join(', ');
}) + ';\n');

const c = rows.app_config[0];
out.push('insert into app_config (id, snacks_baseline, base_calorie_goal, default_prep_days, daily_snack_key, daily_snack_count) values');
out.push('  (1, ' + [jb(c.snacks_baseline), n(c.base_calorie_goal), n(c.default_prep_days), q(c.daily_snack_key), n(c.daily_snack_count)].join(', ') + ');\n');

out.push('commit;');

const dest = path.join(__dirname, '..', 'supabase', 'seed_app.sql');
fs.writeFileSync(dest, out.join('\n') + '\n');
console.log('Wrote ' + dest);
console.log('  ' + rows.stock_ingredients.length + ' ingredients, ' + rows.stock_recipes.length + ' recipes, ' +
    rows.stock_recipe_ingredients.length + ' recipe-ingredient lines, ' + rows.packaging.length + ' packaging, ' +
    rows.week_plans.length + ' week plans.');
